num = int(input("Digite um número:"))
print("-" * 10)
print("{} x {} = {}".format(num,1,num*1))
print("{} x {} = {}".format(num,2,num*2))
print("{} x {} = {}".format(num,3,num*3))
print("{} x {} = {}".format(num,4,num*4))
print("{} x {} = {}".format(num,5,num*5))
print("-" * 10)
